@extends('layouts.frontend.app')
@section('head')
    <title>{{$SiteSetting->meta_title ?? 'Binary Logic'}}</title>
    <meta name="description" content="{{$SiteSetting->meta_des ?? ''}}">
    <meta property="type" content="Website" />
    <link rel="canonical" href="{{$SiteSetting->canonical ?? ''}}/" />
    <meta name="robots" content="{{$SiteSetting->meta_robots ?? ''}}" />
    <meta property="site_name" content="{{$SiteSetting->meta_title ?? ''}}" />

    <meta property="og:url"           content="http://www.beboybd.com/" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="{{$SiteSetting->meta_title ?? ''}}" />
    <meta property="og:description"   content="{{$SiteSetting->meta_des ?? ''}} " />
    <meta property="og:keywords"   content="{{$SiteSetting->meta_keywords ?? ''}} " />
    <meta property="og:image" content="{{ 'https://binarylogic.com.bd/'.$SiteSetting->meta_image ?? ''}}" />
     
     
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@BinaryLogic" />
    <meta name="twitter:creator" content="@BinaryLogic" />
    <meta property="twitter:url" content="http://www.beboybd.com/" />
    <meta property="twitter:title" content="{{$SiteSetting->meta_title ?? ''}}" />
    <meta property="twitter:description" content="{{$SiteSetting->meta_des ?? ''}}" />
    <meta property="twitter:keywords"   content="{{$SiteSetting->meta_keywords ?? ''}} " />
    <meta property="twitter:image" content="{{ 'https://binarylogic.com.bd/'.$SiteSetting->meta_image ?? ''}}" />
    
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Binary Logic",
    "url": "http://binarylogic.com.bd/",
    "logo": "http://www.beboybd.com/images/site_image/Binarylogic_181.png",
    "alternateName": "বাইনারি লজিক",
    "sameAs": [
        "https://www.facebook.com/binarylogic.com.bd",
        "https://www.linkedin.com/company/43266381/admin/",
        "https://www.instagram.com/binarylogic.com.bd/"
    ],
    "contactPoint": [
        {
        "@type": "ContactPoint",
        "telephone": "+8801727061086",
        "contactType": "Technical Support",
        "email": "ecare@binarylogic.com.bd",
        "areaServed": "BD",
        "availableLanguage": "en"
        },
        {
        "@type": "ContactPoint",
        "telephone": "+8801733052212",
        "contactType": "Sales Support",
        "email": "ecare@binarylogic.com.bd",
        "areaServed": "BD",
        "availableLanguage": "en"
        },
        {
        "@type": "ContactPoint",
        "telephone": "+8801733052214",
        "contactType": "Warranty Support",
        "email": "ecare@binarylogic.com.bd",
        "areaServed": "BD",
        "availableLanguage": "en"
        }
    ]
    }
    </script>
@endsection


@section('content')

<style>
    /* .card-type-2 .card__image {
        object-fit: cover !important;
    } */

    img {
        max-width: 100%;
        height: auto
    }
    .text-white{
        color: white;
    }
    
    section{
        padding: 10px;
    }

    .button-optical {
        display: inline-block;
        padding: 1rem 1.25rem 0.75rem 1.25rem;
        border-radius: 10rem;
        color: #fff;
        text-transform: uppercase;
        letter-spacing: .15rem;
        transition: all .3s;
        overflow: hidden;
        z-index: 1;
        background: #4898bf;
        margin: 10px 10px;
    }
    .swiper-pagination-bullet{width: 20px;
    height: 20px;
    background: #ddd;}
    #h-banner,#h-sliderbox{
    height: 350px;
    background: url(images/icon/loading.svg) no-repeat;
    background-size: 100px;
    background-position: 50% 50%;
    }


    @media(max-width: 400px) {
        #top_container .owl-dot span {width: 25px;}
    }

    @media only screen and (max-width: 600px) {
        #h-banner{
            height: 180px;
        }
        #h-sliderbox{
            height: 329px;
        }
        }
        @media only screen and (max-width: 400px) {
        #h-banner{
            height: 150px;
        }
        #h-sliderbox{
            height: 319px;
        }
    }
</style>

<section class="banner-section">
    <div class="container-fluid overflow-hidden">
        <div class="row g-4">
            <div class="col-md-8 mb-4">
                <!-- Swiper -->
                <div class="swiper">
                    <div class="swiper-wrapper">
                        @foreach($banners as $banner)
                        @php
                        $img_arr = explode('/',$banner->image);
                        $img_arr_t = $img_arr[0].'/'.$img_arr[1].'/t/'.$img_arr[2];
                        $img_arr_s = $img_arr[0].'/'.$img_arr[1].'/s/'.$img_arr[2];
                        $img_arr_m = $img_arr[0].'/'.$img_arr[1].'/m/'.$img_arr[2];
                        $img_arr_l = $img_arr[0].'/'.$img_arr[1].'/l/'.$img_arr[2];
                        @endphp
                        <div class="swiper-slide">
                            <a href="{{$banner['url']}}" class="w-100">
                                <picture>
                                    <source srcset="{{asset($img_arr_s)}}" media="(max-width: 480px)">
                                    <source srcset="{{asset($img_arr_s)}}" media="(max-width: 768px)">
                                    <source srcset="{{asset($img_arr_m)}}" media="(max-width: 1024px)">
                                    <source srcset="{{asset($img_arr_m)}}" media="(max-width: 1200px)">
                                    <img src="{{asset($img_arr_l)}}" alt="{{asset($banner->title)}}" class="w-100"/>
                                </picture>
                            </a> 
                        </div>
                        @endforeach
                    </div>
                    <!-- Add Pagination -->
                    <div class="swiper-pagination"></div>
                    <!-- Add Navigation -->
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-md-4">
                <div id="h-sliderbox" class="text-center"></div>
                <!-- /.row -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
</section>
<!-- end of banner section -->

<div class="container-fluid mt-4" style="overflow:hidden">
    <h2 class="section-heading mb-5 mt-4"><a class="text-uppercase" href="http://www.beboybd.com/brands">Our Brands</a></h2>
    <div class="swiper-brand position-relative">
        <div class="swiper-wrapper">
            @foreach($brands as $brand)
            <div class="swiper-slide col-12 px-3">
                <div class="brand">
                    <a href="{{route('/', $brand->slug)}}"><img src="{{asset($brand->image)}}" alt="{{$brand->name}}"></a>
                </div>
            </div>
            @endforeach
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Navigation -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
    <a href="http://www.beboybd.com/brands" class="button-optical">VIEW ALL</a>
</div>


<div class="d-none">
    <div class="slider-headline_container py-4" style="background-color: {{$bgcolors['animated_text_bg']}}">
        <h3 class="cd-headline letters type text-center" 
            style="color: {{$bgcolors['animated_text_font_color']}};font-size: {{$bgcolors['animated_text_fontsize']}};">
            <span>We are the official</span>
            <span class="cd-words-wrapper waiting">
                <b class="is-visible">&nbsp; Intel &nbsp;</b>
                <b>&nbsp; G.Skill &nbsp;</b>
                <b>&nbsp; Orico &nbsp;</b>
                <b>&nbsp; Cooler Master &nbsp;</b>
            </span>
            <span>seller in Bangladesh</span>
        </h3>
    </div>
</div>

    {{-- ad --}}
    @if(count($ads) > 0)
    <div class="container-fluid">
        <div class="row">
            @for ($i = 0; $i < 2; $i++)
            <div class="col-md-6 @if($i == 0) mb-5 mb-md-0 @endif">
                <div @if($i == 0) style="text-align: end;" @else style="text-align: start;" @endif>
                    @if(isset($ads[$i]))
                        <a href="{{ $ads[$i]->cta ?? '' }}">
            <picture>
                <source srcset="{{asset($img_arr_s)}}" media="(max-width: 480px)">
                <source srcset="{{asset($img_arr_s)}}" media="(max-width: 768px)">
                <source srcset="{{asset($img_arr_m)}}" media="(max-width: 1024px)">
                <source srcset="{{asset($img_arr_m)}}" media="(max-width: 1200px)">
                <img src="{{asset($img_arr_l)}}" alt="{{asset($banner->title)}}" class="banner-slider__image w-100"/>
            </picture>
                            <img src="{{ $ads[$i]->image ?? '' }}" alt="" class="lozad-">
                        </a>
                    @endif
                </div>
            </div>
            @endfor
        </div>
    </div>
    @endif
    {{-- ends ad --}}


<div class="container-fluid overflow-hidden">
    <div class="row gx-5">
        <div class="col-md-12">
            <main class="pt-4 pb-4 mb-4">
                <div id="h-offer" style="min-height:715px"></div>
                <div id="h-latest" style="min-height:715px"></div>
                @if(count($ads) > 2)
                <div class="container-fluid">
                    <div class="row">
                        @for ($i = 2; $i < 4; $i++)
                        <div class="col-md-6 @if($i == 2) mb-5 mb-md-0 @endif">
                            <div @if($i == 2) style="text-align: end;" @else style="text-align: start;" @endif>
                                @if(isset($ads[$i]))
                                    <a href="{{ $ads[$i]->cta ?? '' }}">
                                        <img src="{{ $ads[$i]->image ?? '' }}" alt="{{ $i }}" class="lozad-">
                                    </a>
                                @endif
                            </div>
                        </div>
                        @endfor
                    </div>
                </div>
                @endif
                
                <!-- cat -->
                <div id="h-cats-1"></div>
                <!-- end of cat -->

                <!-- <div id="h-brands" class="d-none"></div> -->


                {{-- ad --}}
                @if(count($ads) > 3)
                <div class="container-fluid">
                    <div class="row">
                        @for ($i = 4; $i < 6; $i++)
                        <div class="col-md-6 @if($i == 4) mb-5 mb-md-0 @endif">
                            <div @if($i == 4) style="text-align: end;" @else style="text-align: start;" @endif>
                                @if(isset($ads[$i]))
                                    <a href="{{ $ads[$i]->cta ?? '' }}">
                                        <img src="{{ $ads[$i]->image ?? '' }}" alt="{{ $i }}"  class="lozad-">
                                    </a>
                                @endif
                            </div>
                        </div>
                        @endfor
                    </div>
                </div>
                @endif
                
                <div id="h-posts"></div>
                
            </main>
        </div>

    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" id="product-view">
    </div>
</div>

@endsection